/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AgentSpecification {
    /**
    * The name of the agent that will be used to identify it in the system.
    */
    'name': any | null;
    /**
    * The message that the agent will send to the user when it is first connected
    */
    'systemMessage': any | null;
    /**
    * The list of models that the agent can use to generate responses
    */
    'models'?: any | null;
    /**
    * The list of skills that the agent can apply to the user\'s requests.
    */
    'skills'?: any | null;
    /**
    * A description of the agent for the user to be able to understand what the agent is about.
    */
    'description': any | null;
    /**
    * The cache seed used to initialize the agent\'s random number generator
    */
    'cacheSeed'?: any | null;
    /**
    * The temperature of the agent\'s response generation process
    */
    'temperature'?: any | null;
    'createdAt'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "any",
            "format": ""
        },
        {
            "name": "systemMessage",
            "baseName": "system_message",
            "type": "any",
            "format": ""
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "any",
            "format": ""
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "any",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "any",
            "format": ""
        },
        {
            "name": "cacheSeed",
            "baseName": "cache_seed",
            "type": "any",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentSpecification.attributeTypeMap;
    }

    public constructor() {
    }
}

