/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AgentSpecification {
    /**
    * The name of the agent that will be used to identify it in the system.
    */
    'name': string;
    /**
    * The message that the agent will send to the user when it is first connected
    */
    'systemMessage': string;
    /**
    * The list of models that the agent can use to generate responses
    */
    'models'?: Array<AgentSpecificationModelsEnum>;
    /**
    * The cache seed used to initialize the agent\'s random number generator
    */
    'cacheSeed'?: number;
    /**
    * The temperature of the agent\'s response generation process
    */
    'temperature'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "systemMessage",
            "baseName": "system_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "Array<AgentSpecificationModelsEnum>",
            "format": ""
        },
        {
            "name": "cacheSeed",
            "baseName": "cache_seed",
            "type": "number",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentSpecification.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AgentSpecificationModelsEnum {
    _40125Preview = 'gpt-4-0125-preview',
    _4TurboPreview = 'gpt-4-turbo-preview',
    _41106Preview = 'gpt-4-1106-preview',
    _4 = 'gpt-4',
    _40613 = 'gpt-4-0613',
    _432k = 'gpt-4-32k',
    _432k0613 = 'gpt-4-32k-0613',
    _35Turbo0125 = 'gpt-3.5-turbo-0125',
    _35Turbo = 'gpt-3.5-turbo',
    _35Turbo1106 = 'gpt-3.5-turbo-1106',
    _35TurboInstruct = 'gpt-3.5-turbo-instruct'
}

