/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocalLlmModel } from '../models/LocalLlmModel';
import { OpenAILlmModel } from '../models/OpenAILlmModel';
import { HttpFile } from '../http/http';

export class AgentSpecificationModelsInner {

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
    ];

    static getAttributeTypeMap() {
        return AgentSpecificationModelsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

