/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CodeAndIgnore {
    'ignore'?: any | null;
    /**
    * The code that will be used to execute the agent.
    */
    'code': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ignore",
            "baseName": "ignore",
            "type": "any",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CodeAndIgnore.attributeTypeMap;
    }

    public constructor() {
    }
}

