/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Name } from '../models/Name';
import { PhoneNumber } from '../models/PhoneNumber';
import { PhotoUrl } from '../models/PhotoUrl';
import { HttpFile } from '../http/http';

export class FirebaseUser {
    'uid': any | null;
    'email': any | null;
    'disabled'?: any | null;
    'emailVerified'?: any | null;
    'customClaims'?: any | null;
    'name': Name;
    'photoUrl': PhotoUrl;
    'phoneNumber': PhoneNumber;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uid",
            "baseName": "uid",
            "type": "any",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "any",
            "format": ""
        },
        {
            "name": "emailVerified",
            "baseName": "email_verified",
            "type": "any",
            "format": ""
        },
        {
            "name": "customClaims",
            "baseName": "custom_claims",
            "type": "any",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Name",
            "format": ""
        },
        {
            "name": "photoUrl",
            "baseName": "photo_url",
            "type": "PhotoUrl",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "PhoneNumber",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FirebaseUser.attributeTypeMap;
    }

    public constructor() {
    }
}

