/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum GroqLlmModel {
    Mixtral8x7b32768 = 'mixtral-8x7b-32768',
    Llama270b4096 = 'llama2-70b-4096'
}
