/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class HasRequirements {
    /**
    * The list of requirements that the agent must satisfy in order to be used.
    */
    'requirements': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requirements",
            "baseName": "requirements",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HasRequirements.attributeTypeMap;
    }

    public constructor() {
    }
}

