/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelDetails } from '../models/ModelDetails';
import { HttpFile } from '../http/http';

export class ModelProviderConnection {
    'name': string;
    'logo': string;
    'apiUrl': string;
    'apiKeyUrl': string;
    'models': Array<ModelDetails>;
    'id': string;
    'isConnected': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiUrl",
            "baseName": "api_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKeyUrl",
            "baseName": "api_key_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "Array<ModelDetails>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isConnected",
            "baseName": "isConnected",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelProviderConnection.attributeTypeMap;
    }

    public constructor() {
    }
}

