/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum OpenAILlmModel {
    _40125Preview = 'gpt-4-0125-preview',
    _4TurboPreview = 'gpt-4-turbo-preview',
    _41106Preview = 'gpt-4-1106-preview',
    _4 = 'gpt-4',
    _40613 = 'gpt-4-0613',
    _432k = 'gpt-4-32k',
    _432k0613 = 'gpt-4-32k-0613',
    _35Turbo0125 = 'gpt-3.5-turbo-0125',
    _35Turbo = 'gpt-3.5-turbo',
    _35Turbo1106 = 'gpt-3.5-turbo-1106',
    _35TurboInstruct = 'gpt-3.5-turbo-instruct'
}
