/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SavedMessageModel {
    /**
    * The content of the message.
    */
    'content': string;
    'role'?: string | null;
    /**
    * The identifier of the sender of the message.
    */
    'sender': string;
    /**
    * The date and time the message was sent.
    */
    'sentAt': string;
    /**
    * The unique identifier of the message.
    */
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "string",
            "format": ""
        },
        {
            "name": "sentAt",
            "baseName": "sent_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SavedMessageModel.attributeTypeMap;
    }

    public constructor() {
    }
}

