/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentSpecificationModelsInner } from '../models/AgentSpecificationModelsInner';
import { HttpFile } from '../http/http';

export class SavedAgentSpecification {
    /**
    * The name of the agent that will be used to identify it in the system.
    */
    'name': string;
    /**
    * The message that the agent will send to the user when it is first connected
    */
    'systemMessage': string;
    /**
    * The list of models that the agent can use to generate responses
    */
    'models'?: Array<AgentSpecificationModelsInner>;
    /**
    * A description of the agent for the user to be able to understand what the agent is about.
    */
    'description': string;
    /**
    * The cache seed used to initialize the agent\'s random number generator
    */
    'cacheSeed'?: number;
    /**
    * The temperature of the agent\'s response generation process
    */
    'temperature'?: number;
    'createdAt'?: string;
    'id': string;
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "systemMessage",
            "baseName": "system_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "Array<AgentSpecificationModelsInner>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "cacheSeed",
            "baseName": "cache_seed",
            "type": "number",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SavedAgentSpecification.attributeTypeMap;
    }

    public constructor() {
    }
}

