/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SavedAgentSpecification } from '../models/SavedAgentSpecification';
import { SavedMessageModel } from '../models/SavedMessageModel';
import { HttpFile } from '../http/http';

export class Session {
    'id': string;
    'agents': Array<SavedAgentSpecification>;
    'messages': Array<SavedMessageModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "agents",
            "baseName": "agents",
            "type": "Array<SavedAgentSpecification>",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<SavedMessageModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Session.attributeTypeMap;
    }

    public constructor() {
    }
}

