/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Session {
    'id': any | null;
    'agents': any | null;
    'messages': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any",
            "format": ""
        },
        {
            "name": "agents",
            "baseName": "agents",
            "type": "any",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Session.attributeTypeMap;
    }

    public constructor() {
    }
}

