/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SkillSpecification {
    /**
    * The name of the skill that will be used to identify it in the system.
    */
    'name': any | null;
    /**
    * The description of the skill that will be used to describe it in the system.
    */
    'description'?: any | null;
    /**
    * The list of requirements that the skill must satisfy in order to be used.
    */
    'requirements'?: any | null;
    /**
    * The code that will be used to execute the agent.
    */
    'code': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "any",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "any",
            "format": ""
        },
        {
            "name": "requirements",
            "baseName": "requirements",
            "type": "any",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SkillSpecification.attributeTypeMap;
    }

    public constructor() {
    }
}

