/**
 * Agents as a Service
 * API for the Agents as a Service project
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidationErrorLocInner } from '../models/ValidationErrorLocInner';
import { HttpFile } from '../http/http';

export class ValidationError {
    'loc': Array<ValidationErrorLocInner>;
    'msg': string;
    'type': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "loc",
            "baseName": "loc",
            "type": "Array<ValidationErrorLocInner>",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationError.attributeTypeMap;
    }

    public constructor() {
    }
}

