
### Authenticate user
POST http://{{host}}/api/auth
Authorization: Basic cm9iZXJ0QGhqb3J0c2hvbG0uY29tOlRlc3QxMjM=

> {%
    const body = response.body.toString();
    client.global.set("access_token", body);
%}