### List sessions
GET {{host}}/api/sessions
Authorization: Bearer {{access_token}}
Content-Type: application/json



### Create session
POST {{host}}/api/sessions
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "agents": [
    "5BQYLmwIxTmgn09f85zn"
  ]
}


### Get session
GET {{host}}/api/sessions/CLYdq0WcIcpeYz26moCb
Authorization: Bearer {{access_token}}


### Send message in session
### Todo change this message to a json object with the message, this way it can be used by ChatGPT as well
POST {{host}}/api/sessions/CLYdq0WcIcpeYz26moCb
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "content": "Can you write and run a python script to get the stock price of Tesla (TSLA)?"
}
