### Authenticate with username and password
POST https://{{host}}/api/auth
Authorization: Basic cm9iZXJ0QGhqb3J0c2hvbG0uY29tOlRlc3QxMjM=

### Get authenticated user
GET https://{{host}}/api/auth
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjUzZWFiMDBhNzc5MTk3Yzc0MWQ2NjJmY2EzODE1OGJkN2JlNGEyY2MiLCJ0eXAiOiJKV1QifQ.eyJhZG1pbiI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FnZW50cy1hcy1hLXNlcnZpY2UiLCJhdWQiOiJhZ2VudHMtYXMtYS1zZXJ2aWNlIiwiYXV0aF90aW1lIjoxNzA3MDQ4NjUwLCJ1c2VyX2lkIjoiV3p3Q09FRmxlR09ZdXhxTUd4R2xqNEM5NWxVMiIsInN1YiI6Ild6d0NPRUZsZUdPWXV4cU1HeEdsajRDOTVsVTIiLCJpYXQiOjE3MDcwNDg2NTAsImV4cCI6MTcwNzA1MjI1MCwiZW1haWwiOiJyb2JlcnRAaGpvcnRzaG9sbS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicm9iZXJ0QGhqb3J0c2hvbG0uY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.XGbmI5-cFjwgU50fdl2s92SoQPlFtmbhjcQ3X4Z4d6MTtBzETFBi4DWIxpL3VMsKoUMQIQQ4TVM8QTtuJPzTiKmNQGv_ZC9LfmL8gZCwiD15ocVXK-X0N2xJ9eJdeu2icxI6qWrqcF8-W8m_5T4Hu26NaaRvZymfuKXTOWPtIlB3sJl5lCOaS2DxXjAwDjDrSpznDBb8O7QoVczROvevNNVA-A5LaxsBfyY3MzY7X1UkTXDmxxqClIVzqDxx86_8peGd1bN1WsNtGIODmcr2M58Ygpilj7MmGd6PZrKmlcQngMxgICKBmX10MSNARMQLolcBdEN3P8KIdGrE1LuHjg
